name: Push Container to Heroku
​
on:
  push:
    branches:
      - development
​
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "radiant-scrubland-16107"
          heroku_email: "shingim1@gmail.com"